Milestone-2
AkintoyeOlamide/Bookstore-react pull request #3
Opened 2021-08-03 07:54 UTC by AkintoyeOlamide

In this milestone, I  initialized the Redux actions, reducers, and store. Additionally, and also defined empty React components.

2021-08-03 13:29 UTC, oloomoses requested changes
Hi @AkintoyeOlamide, 

Good job so far!
There are some issues that you still need to work on to go to the next project, but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_Slack: Oloo Moses_

2021-08-03 13:29 UTC, oloomoses commented on src/components/book.js
> +  };
- [ ] The Book component is a presentational component. This means that it should not interact directly with the redux store and the state should be passed down to it as a prop. You don't need to have the provider and the store here since this has already been implemented in `src/index.js`.Kindly delete these.

2021-08-03 13:29 UTC, oloomoses commented on src/components/book.js
> +      </div>
- [ ] Kindly let's ensure that the Book component only represents a single row of books with id, title, and category  as per the [requirements from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/Book/RepresentARowInBooksTable.png)
- [ ] I can tell that you have really worked on this component's layout. However, It is important that you stick to the given project requirements. You can always improve on the project after its completion and approval

2021-08-03 13:29 UTC, oloomoses commented on src/components/book.js
> +    </div>
- [ ] Kindly let's ensure that the Book component only represents a single row of books with id, title, and category  as per the [requirements from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/Book/RepresentARowInBooksTable.png)
- [ ] I can tell that you have really worked on this component's layout. However, It is important that you stick to the given project requirements. You can always improve on the project after its completion and approval

2021-08-03 13:29 UTC, oloomoses commented on src/components/categorySelect.js
> +export default connect(mapStateToProps, mapDispatchToProps)(categorySelect);
Since this is a presentational component and does not directly interact with the state, you don't need these methods. Kindly delete them.

2021-08-03 13:29 UTC, oloomoses commented on src/components/editBook.js
> +/* eslint-disable react/style-prop-object */
- [ ] Kindly ensure that you don't overuse the linter disable. Linters are meant to enforce code quality and too much linter disable means that there is something wrong.

2021-08-03 13:29 UTC, oloomoses commented on src/components/book.js
> +/* eslint-disable jsx-a11y/anchor-is-valid */
- [ ] Kindly ensure that you don't overuse the linter disable. Linters are meant to enforce code quality and too much linter disable means that there is something wrong.

2021-08-03 13:29 UTC, oloomoses commented on src/containers/booklist.js
> +/* eslint-disable react/jsx-key */
- [ ] Kindly ensure that you don't overuse the linter disable. Linters are meant to enforce code quality and too much linter disable means that there is something wrong.

2021-08-03 13:29 UTC, oloomoses commented on src/containers/booklist.js
> +import Book from '../components/book';
- [ ] Kindly let's check all the imports and ensure that they are correct. Here you are importing `Book` that is starting with caps and the function starts with a small letter `const book = (props) => `

2021-08-03 13:29 UTC, oloomoses commented on src/containers/booklist.js
> +    </div>
- [ ] Kindly let's update this to display books list in HTML table using `Book` component as per the [requirements from pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/BooksList/BooksAsTable.png)
- [ ] Also let's ensure that we pass a `book` object as a prop to each `Book` component

2021-08-03 13:29 UTC, oloomoses commented on src/containers/bookform.js
> +  const [chapterName, setChapterName] = useState('');
- [ ] Kindly delete these and ensure that you use redux to handle all the states

2021-08-05 00:35 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED 🟡  ♻️

Hi @AkintoyeOlamide, great work on making some of the changes requested by the previous reviewer 👏 , however, there are still some issues that need to be addressed before this milestone is approved.Kindly check my comments below ⬇️ 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-08-05 00:35 UTC, Elbie-em commented on src/actions/index.js
> +export const REMOVE_BOOK = 'REMOVE_BOOK';
- [x] I noticed you have declared these action types in `src/action-type/index.js` to follow the DRY concept kindly import them instead of declaring them and reuse them where required.

2021-08-05 00:35 UTC, Elbie-em commented on src/components/Book.js
> +      </button>
- [ ] I noticed you went the extra mile and added the remove button along with its functionality, but as the previous reviewer stated, **It is important that you stick to the given project requirements**, in this case, kindly use this milestone's requirements strictly.

2021-08-05 00:35 UTC, Elbie-em commented on src/container/BookList.js
> +export default booksReducer;
- [x] Kindly remove this unused file as I see you have the `BookList` component and `booksReducer `in their respective directories. It is good to always remove files or pieces of code that may confuse other developers trying to read your code.

2021-08-05 00:35 UTC, Elbie-em commented on src/container/Bookform.js
> +export default BooksForm;
- [x]  Kindly remove this unused file as I see you have the BookForm component in its respective directory. It is good to always remove files or pieces of code that may confuse other developers trying to read your code.

2021-08-05 00:35 UTC, Elbie-em commented on src/containers/BookList.js
> +/*eslint-disable */
- [x] Kindly enable eslint. Linters are meant to enforce code quality as pointed out by the previous reviewer

2021-08-05 00:35 UTC, Elbie-em commented on src/containers/BooksForm.js
> +  };
- [x]  I noticed this `handleAddbook` function and its calling on the `Create Book` button, kindly stick to the requirements of this milestone as mentioned earlier.

2021-08-05 00:35 UTC, Elbie-em commented on src/reducers/book.js
> +export default booksReducer;
- [x] Kindly remove this duplicate reducer, having files and pieces of code that are not being used makes your codebase hard to read.

2021-08-05 00:35 UTC, Elbie-em commented on src/reducers/books.js
> +
#### [OPTIONAL]

- [x] I highly recommend setting the titles and categories of the books to values that align to what they could be for this project e:g
```
  {
    ID: 3,
    title: 'Alice in wonderland',
    category: 'Fantasy',
  },
```

2021-08-05 08:00 UTC, AkintoyeOlamide commented on src/containers/BooksForm.js
> +  };
Please I don't seem to understand the requirement as stated by the previous TSE, could please kindly enlighten me as pathwright didn't specifically say it, or maybe I am missing it, could you maybe also kindly show me so I will understand better?

2021-08-05 08:19 UTC, AkintoyeOlamide commented on src/containers/BookList.js
> +/*eslint-disable */
I have removed the eslint disabled, but my npx eslint will come back with errors that I can not correct until milestone 3

2021-08-05 08:47 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Well done making the requested changes. Let's fix a few things before merging.

### Changes 🔕 🔕 🔕 
- fix failing linter cases
- remove the `src/container` folder. This folder contains redundant code that already exists in `src/containers`. Always keep your codebase clean.

#### Note: Seek clarification from a reviewer on slack in case of confusion regarding their review.

### Martin Afani
#### Slack: whiz25

2021-08-05 09:03 UTC, afanimartin approved these changes
## Approved 👍🏿 👍🏿 👍🏿 
Unnecessary folder deleted and linter errors fixed. Merge and proceed to the next milestone.


### Martin Afani
#### Slack: whiz25

2021-08-05 09:59 UTC, merged