Milestone 3
AkintoyeOlamide/Bookstore-react pull request #4
Opened 2021-08-05 12:51 UTC by AkintoyeOlamide

In this milestone, I connected the CREATE_BOOK and REMOVE_BOOK
actions with the React component and make the page dynamic.

2021-08-05 14:03 UTC, rindrajosia requested changes
Hi, 

Good job so far!
There are some issues to revise before continuing to the next project but hang in there and read the comments below with care. You can do it! :muscle:


## Required Changes ♻️

- [x] I got an error related to your prop-types when I open your APP on my browser, please fix it.
![1](https://user-images.githubusercontent.com/58552748/128361890-cc2f5efb-308c-4991-a4f1-491faae940cc.gif)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-08-05 14:03 UTC, rindrajosia commented on src/containers/BookList.js
> -/* eslint-disable */
- [x] [REQUIRED] Please don't disable eslint. It is like making some changes in the linter file.

2021-08-05 14:03 UTC, rindrajosia commented on src/containers/BookList.js
>      });
- [ ] [REQUIRED] it connects the REMOVE_BOOK action. In fact, you have already a REMOVE_BOOK action inside `src/actions/index.js` so, You don't need to redefine it.

2021-08-05 14:03 UTC, rindrajosia commented on src/containers/BooksForm.js
> +/*eslint-disable */
- [x] [REQUIRED] Please don't disable eslint. It is like making some changes in the linter file.

2021-08-06 11:40 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Hey, good job making the requested changes. 
I ran your app locally and got this error: 
![Screenshot from 2021-08-06 13-38-22](https://user-images.githubusercontent.com/80149314/128505170-cf666827-55c2-4b39-ac2e-fbcf8db8ebad.png)
Fix and send another request. Good luck


### Martin Afani
#### Slack: whiz25

2021-08-06 12:04 UTC, rindrajosia requested changes
Hi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️

- [ ] [REQUIRED] The error related to the prop-types reappears. Please fix it:
![1](https://user-images.githubusercontent.com/58552748/128507362-cb124a68-ecae-44ce-a93a-a8be8a5ff8c6.gif)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------

2021-08-06 12:04 UTC, rindrajosia commented on src/containers/BooksForm.js
> +/*eslint-disable */
- [ ] [REQUIRED] Please `don't disable eslint`. It is like making changes in the linter config.

2021-08-06 12:04 UTC, rindrajosia commented on src/containers/BookList.js
>      });
It will be nice if you work on it

2021-08-09 15:44 UTC, whiz25 requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Fix the linter errors and submit for another review. No PR can be approved when linters checks are failing.


### Martin Afani
#### Slack: whiz25

2021-08-10 08:47 UTC, whiz25 approved these changes
## Approved 👍🏿 👍🏿 👍🏿 
Nice work making the requested changes. All linter errors have been fixed.


### Martin Afani
#### Slack: whiz25

2021-08-10 12:05 UTC, merged